# Generated by Django 3.0 on 2020-01-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date1',
        ),
    ]
